before_script:
  - export SYSTEM_VERSION=$CI_COMMIT_REF_NAME-v1.0.0

stages:
  - config
  - build
  - deploy

config work[dev]:
  stage: config
  only:
    - dev
  tags:
    - test-cicd-tag
  script:
    - ls
    - kubectl --kubeconfig=~/.kube/config create configmap dev-cicdtest-config -n testns --from-file etc/config.dev.json --dry-run=client -o yaml | kubectl apply -f -

config work[test]:
  stage: config
  only:
    - test
  tags:
    - test-cicd-tag
  script:
    - kubectl create configmap dev-cicdtest-config -n testns --from-file etc/config.test.json --dry-run=client -o yaml | kubectl apply -f -

build work - system:
  stage: build
  tags:
    - test-cicd-tag
  script:
    - echo "build hello"

deploy work - system[dev]:
  stage: deploy
  only:
    - dev
  tags:
    - test-cicd-tag
  script:
    - echo "deploy-dev hello"

deploy work - system[test]:
  stage: deploy
  only:
    - test
  tags:
    - test-cicd-tag
  script:
    - echo "deploy-test hello"
