before_script:
  - export SYSTEM_VERSION=$CI_COMMIT_REF_NAME
  - export CI_PIPELINE_ID=CI_PIPELINE_ID
  - export CI_COMMIT_SHA=CI_COMMIT_SHA
  - export CI_PROJECT_ID=CI_PROJECT_ID
  - export CI_PROJECT_NAME=CI_PROJECT_NAME
  - export CI_JOB_ID=CI_JOB_ID
  - export CI_RUNNER_DESCRIPTION=CI_RUNNER_DESCRIPTION
  - export CI_RUNNER_TAGS=CI_RUNNER_TAGS
  - export CI_COMMIT_MESSAGE=CI_COMMIT_MESSAGE
  - export CI_PIPELINE_SOURCE=CI_PIPELINE_SOURCE

stages:
  - build

job:
  stage: build
  script:
    - echo "当前提交的分支或标签名称 $SYSTEM_VERSION"
    - echo "当前流水线的唯一ID CI_PIPELINE_ID"
    - echo "当前提交的 SHA 标识 CI_COMMIT_SHA"
    - echo "当前项目的唯一 ID CI_PROJECT_ID"
    - echo "当前项目的名称 CI_PROJECT_NAME"
    - echo "当前作业的唯一 ID CI_JOB_ID"
    - echo "运行作业的 GitLab Runner 的描述 CI_RUNNER_DESCRIPTION"
    - echo "运行作业的 GitLab Runner 的标签 CI_RUNNER_TAGS"
    - echo "当前提交的提交信息 CI_COMMIT_MESSAGE"
    - echo " 触发流水线的来源 CI_PIPELINE_SOURCE"

