stages:
  - build
  - test
  - deploy

module-a-build:
  stage: build
  script:
    - echo "hello module-a-build"
    - sleep 10

module-b-build:
  stage: build
  script:
    - echo "hello module-b-build"
    - sleep 10

module-a-test:
  stage: test
  script:
    - echo "hello module-a-test"
    - sleep 10
  needs: ["module-a-build"]

module-b-test:
  stage: test
  script: 
    - echo "ehllo module-b-test"
    - sleep 10
  needs: 
    - job: ["module-b-build"]
      artifacts: tre