stages:
  - build
  - run

workflow:
  rules:
    - if: `$CI_PIPELINE_SOURCE  == "push"`
      when: never

build-job:
  stage: build
  script:
    - docker build . -t cicd-test

run-job:
  stage: run
  script:
    - docker run -d -p 9999:9999 --name t1 cicd-test