stages:
  - build
  - run

workflow:
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
      when: always
    - if: '$CI_PIPELINE_SOURCE  == "push"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "pull_request"'
      when: always

build-job:
  stage: build
  script:
    - docker build . -t cicd-test
  artifacts:
    paths:
      - cicd-test.tar

run-job:
  stage: run
  script:
    - docker run -d -p 9999:9999 --name t1 cicd-test