stages:
  - build

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - export CI_REGISTRY_AUTH_API_IMAGE="loveyu233/cicd:${SYSTEM_VERSION}"
    - export CI_DOCKERFILE="$CI_PROJECT_DIR/Dockerfile"
    - export CI_REGISTRY_AUTH_API="https://index.docker.io/v1/"
    - export CI_REGISTRY_USERNAME="loveyu22333@gmail.com"
    - export CI_REGISTRY_PASSWORD="lovexiang233.."
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY_AUTH_API}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USERNAME}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --insecure-pull --insecure --context "${CI_PROJECT_DIR}" --dockerfile "${CI_DOCKERFILE}" --destination "${CI_REGISTRY_AUTH_API_IMAGE}"

