stages:
  - build
  - run

cache:
  paths:
    - target/*



job-run:
  stage: run
  script: 
    - echo "run" > target/run.txt
    - ls
    - tar -cvf target.tar target
  artifacts:
    paths:
      - target
