before_script:
  - export SYSTEM_VERSION=$CI_COMMIT_REF_NAME-v1.0.0

stages:
  - config
  - build
  - deploy

config work[dev]:
  stage: config
  only:
    - release-dev
  tags:
    - k8s-group-dev
  script:
    - kubectl create configmap dev-cicdTest-config -n testNS --from-file etc/config.dev.json --dry-run -o yaml | kubectl apply -f -

config work[test]:
  stage: config
  only:
    - release-test
  tags:
    - k8s-group-test
  script:
    - kubectl create configmap dev-cicdTest-config -n testNS --from-file etc/config.test.json --dry-run -o yaml | kubectl apply -f -

build work - system:
  stage: build
  tags:
    - k8s-group-build
  script:
    - echo "build hello"

deploy work - system[dev]:
  stage: deploy
  tags:
    - k8s-group-dev
  script:
    - echo "deploy-dev hello"

deploy work - system[test]:
  stage: deploy
  tags:
    - k8s-group-test
  script:
    - echo "deploy-test hello"